# permissions for end users to edit kryptons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krypton-editor-role
rules:
- apiGroups:
  - qingcloud.com
  resources:
  - kryptons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qingcloud.com
  resources:
  - kryptons/status
  verbs:
  - get
